namespace AncinInsaat.Services;

// Derives a thumbnail's path from an original's, per the project image
// architecture (docs/07_AssetStructure.md): every "originals" folder has a
// sibling "thumbnails" folder holding a same-name WebP copy, generated by
// ThumbnailTool (tools/ThumbnailTool) or, later, the Admin Panel's upload
// pipeline via AncinInsaat.ImagePipeline.ThumbnailGenerator. Pure path
// string manipulation — no schema field stores this, since it's always
// mechanically derivable from ImagePath/CoverImage.
public static class ImagePathHelper
{
    public static string GetThumbnailPath(string originalPath)
    {
        var thumbnailFolderPath = originalPath.Replace("/originals/", "/thumbnails/");
        return Path.ChangeExtension(thumbnailFolderPath, ".webp");
    }
}
